const SERVER_RESPONSE = {
  AUTH: "AUTH",
  SIGNUP: "SIGNUP",
  USR_MSG: "USR_MSG",
  USR_CHATS: "USR_CHATS",
  USRS_IN_CHAT: "USRS_IN_CHAT",
  CREATE_GROUP: "CREATE_GROUP",
  JOIN_GROUP: "JOIN_GROUP",
  GET_LOST_MESSAGES: "GET_LOST_MESSAGES",
};

export default SERVER_RESPONSE;
